# Generated by Django 2.0.13 on 2020-09-14 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField()),
                ('num_like', models.IntegerField(max_length=5)),
                ('num_read', models.IntegerField(max_length=5)),
                ('num_reply', models.IntegerField(max_length=5)),
                ('is_blind', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('p_dp', models.FloatField(max_length=5)),
                ('a_da', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('prob_slang', models.FloatField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='post.MemberInfo')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
