# Generated by Django 2.0.13 on 2020-09-14 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField()),
                ('num_like', models.IntegerField(max_length=5)),
                ('num_read', models.IntegerField(max_length=5)),
                ('num_reply', models.IntegerField(max_length=5)),
                ('is_blind', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('p_dp', models.FloatField(max_length=5)),
                ('a_da', models.FloatField(max_length=5)),
                ('temp', models.FloatField(max_length=5)),
                ('prob_slang', models.FloatField(max_length=5)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='MemberInfo',
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.MemberInfo'),
        ),
    ]
