# Generated by Django 2.0.13 on 2020-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200914_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='classification',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
