# Generated by Django 3.1.1 on 2020-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='text',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
